development: &development
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: prehrana_development

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: prehrana_test

production:
  <<: *development
